# myspace-api CI/CD pipeline
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize]

jobs:

  avoid_redundancy:
    name: Avoid redundancy
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - if: ${{ github.ref_name == 'main' }}
        name: Build with Maven Prod Env
        run: mvn -B clean package -DskipTests -P prod
      - if: ${{ github.ref_name == 'develop' }}
        name: Build with Maven Dev Env
        run: mvn -B clean package -DskipTests -P dev
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/myspace-0.0.1-SNAPSHOT.jar

  tests:
    name: Execute Tests
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Execute Tests
        run: mvn -B clean test

  build-push-docker-image:
    name: Push Docker Image to Docker Hub
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: [tests]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven Prod Env
        run: mvn -B clean package -DskipTests -P prod
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest
          cache-to: type=inline
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest
          build-args: PROFILE=prod

  deploy:
    name: Deploy to Elastic Beanstalk
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: [tests]
    runs-on: ubuntu-22.04
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: myspace
          environment_name: prod
          version_label: ${{github.SHA}}
          region: eu-west-3
          deployment_package: myspace-0.0.1-SNAPSHOT.jar